### ISSUE TITLE
Bug POLLING_OK?

### ISSUE THREAD

**Issue by ParkFramework** [m6w6/ext-pq#21]
Test for `php-cli`
```php
<?php

use pq\Connection;

$db   = new Connection('user=postgres application_name=Test', Connection::ASYNC);

$dbIo = new EvIo($db->socket, Ev::READ, function() use($db)
{
	try
	{
		echo "Connect PostgreSQL server...\r\n";

		if($db->poll() === Connection::POLLING_OK)
		{
			echo "Restart PostgreSQL server...\r\n";

			exec('systemctl restart postgresql-9.6');

			if($db->poll() === Connection::POLLING_OK)
			{
				echo "IS BUG - POLLING_OK\r\n";

				try
				{
					$db->execAsync('');
				}
				catch(Throwable $e)
				{
					exit("Error: ".$e->getMessage()."\r\n");
				}
			}

			exit("IS OK\r\n");
		}
	}
	catch(Throwable $e)
	{
		echo "Error: ".$e->getMessage()."\r\n";
	}
});

$db->poll();
Ev::run();
```

**Comment by DaveRandom** [comment]
Can you explain what this snippet is trying to test? What scenario are you expecting this to happen in?

If anything this is a bug in libpq, as poll() is just passing through the return value of `PQconnectPoll()` at this point - but since you've already connected, I'd imagine that libpq is short-circuiting the return value because it knows it's already connected and doesn't have any work left to do.

You'd need to watch the socket for readability and detect the disconnect, you can't just poll the connection again.

If you'd like some reference on the programming flow, check out https://github.com/amphp/pgsql/tree/new-api/src - it's not thoroughly tested but it's known to work with everything I've thrown at it so far.

**Comment by ParkFramework** [comment]
> Can you explain what this snippet is trying to test? What scenario are you expecting this to happen in?

`PQconnectPoll ()` must return FAILED,  it does it if has already been executed at least one sql query.

> You'd need to watch the socket for readability and detect the disconnect, you can't just poll the connection again.

Where can I see an example?

**Comment by m6w6** [comment]
Hey!

`POLLING_OK` just means nothing to write or read left, and as far as client/server communication is concerned everything has successfully been transmitted.

You **cannot** test for a broken connection **except** with a real action on the connection like an empty query.

HTH

**Comment by m6w6** [comment]
Ah, FYI, here's the complete procedure about how to finish an asynchronous connect:
https://mdref.m6w6.name/pq/Connection/:%20Asynchronous%20Usage#Complete.asynchronous.operation:

**Comment by ParkFramework** [comment]
> You cannot test for a broken connection except with a real action on the connection like an empty query.

Okay :)
